# Generated by Django 3.0.6 on 2020-08-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverydetailswi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delupdate',
            name='conno',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
