# Generated by Django 3.0.6 on 2020-07-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recievedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfno', models.CharField(max_length=12)),
                ('date', models.DateField()),
                ('conno', models.CharField(max_length=12)),
                ('pcs', models.IntegerField()),
                ('wt', models.IntegerField()),
            ],
        ),
    ]
