# Generated by Django 3.0.6 on 2020-07-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recdata', '0002_auto_20200718_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recievedata',
            name='conno',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='recievedata',
            name='mfno',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
