# Generated by Django 3.0.6 on 2020-08-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recdata', '0006_auto_20200802_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifestnumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest', models.CharField(max_length=15)),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
    ]
