# Generated by Django 3.0.6 on 2020-08-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recdata', '0007_manifestnumbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestnumbers',
            name='closed',
            field=models.BooleanField(default=True),
        ),
    ]
