# Generated by Django 3.0.6 on 2020-07-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecievedDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivereddate', models.DateField()),
                ('recievedby', models.CharField(max_length=100)),
                ('consignmentnumber', models.CharField(max_length=20)),
            ],
        ),
    ]
