# Generated by Django 3.0.6 on 2020-07-30 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('delivereddetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieveddetails',
            name='pcs',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recieveddetails',
            name='wt',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
