# Generated by Django 3.0.6 on 2020-07-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivereddetails', '0006_auto_20200730_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieveddetails',
            name='delivereddate',
            field=models.CharField(max_length=30),
        ),
    ]
