# Generated by Django 3.0.6 on 2020-08-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivereddetails', '0007_auto_20200730_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieveddetails',
            name='recievedby',
            field=models.CharField(max_length=50),
        ),
    ]
